services:
  backend:
    image: ghcr.io/pdiegmann/opet/backend:latest
    restart: unless-stopped
    container_name: backend
    ports:
      - "3001:3001"
    networks:
      - homelab_network
    volumes:
      - opet_data:/var/lib/opet
    env_file:
      - .env
    environment:
      DATABASE_URL: file:/var/lib/opet/opet.db
      PORT: 3001
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab_network"
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.http.routers.opet-backend.rule=Host(`opet.hnnl.eu`) && PathPrefix(`/api`)"
      - "traefik.http.routers.opet-backend.entrypoints=websecure"
      - "traefik.http.routers.opet-backend.tls=true"
      - "traefik.http.routers.opet-backend.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
      - "traefik.http.services.opet-backend.loadbalancer.server.port=3001"

  frontend:
    image: ghcr.io/pdiegmann/opet/frontend:latest
    restart: unless-stopped
    container_name: frontend
    ports:
      - "3080:8080"
    networks:
      - homelab_network
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab_network"
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.http.routers.opet-frontend.rule=Host(`opet.hnnl.eu`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.opet-frontend.entrypoints=websecure"
      - "traefik.http.routers.opet-frontend.tls=true"
      - "traefik.http.routers.opet-frontend.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
      - "traefik.http.services.opet-frontend.loadbalancer.server.port=8080"

volumes:
  opet_data:

networks:
  homelab_network:
    external: true